version: '3.8'

services:
  115docker:
    build: .
    image: 115docker:unraid
    container_name: 115docker
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp:unconfined
    shm_size: 1gb
    environment:
      PUID: 99
      PGID: 100
      UMASK: "000"
      DOWNLOAD_PERMISSION_FIX: "1"
      DOWNLOAD_PERMISSION_FIX_INTERVAL: "30"
      DOWNLOAD_FILE_MODE: "666"
      DOWNLOAD_DIR_MODE: "777"
      PASSWORD: "123456"
      DISPLAY_WIDTH: "1920"
      DISPLAY_HEIGHT: "1080"
      COOKIE_CID: "xxxxxxxxx"
      COOKIE_SEID: "xxxxxxxx"
      COOKIE_UID: "xxxxxxxxx"
      COOKIE_KID: "xxxxxxxxx"
      TZ: "Asia/Shanghai"
      LC_ALL: "zh_CN.UTF-8"
    volumes:
      - /mnt/user/appdata/115docker:/etc/115
      - /mnt/user/downloads:/opt/Downloads
